# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz.xci
# IP: The module: 'clk_10mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10mhz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz.xci
# IP: The module: 'clk_10mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/ip/clk_10mhz/clk_10mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
