# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/takas/src/R4/vivado/R4_hello/R4_hello.cache/wt [current_project]
set_property parent.project_path C:/Users/takas/src/R4/vivado/R4_hello/R4_hello.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/takas/src/R4/vivado/R4_hello/R4_hello.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/takas/src/R4/alu.sv
  C:/Users/takas/src/R4/cpu.sv
  C:/Users/takas/src/R4/decoder.sv
  C:/Users/takas/src/R4/immgen.sv
  C:/Users/takas/src/R4/regfile.sv
  C:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/sources_1/new/R4_hello_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/takas/src/R4/vivado/R4_hello/R4_hello.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top R4_hello_top -part xc7a35tcpg236-1 -directive AreaOptimized_high -control_set_opt_threshold 1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef R4_hello_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file R4_hello_top_utilization_synth.rpt -pb R4_hello_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
